name: updateec2
on:
  workflow_dispatch:
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOST_IP: 54.88.15.105
            USER_NAME: ubuntu
      
        run: |
          echo "$USER"
          #sudo echo $PRIVATE_KEY  | tee private_key.pem
          #sudo chmod 600 private_key.pem
          #cat private_key.pem
    
          '
